version: '3'
services:
  webdacsramon:
    image: ramondacs2022:latest
    depends_on:
      - "dbramon"
    ports:
      - "8092:8081"
    links:
      - dbramon
    environment:
      DB_HOST: 'dbramon:3306'
      DB_USER: 'root'
      DB_PASSWORD: 'root'
      DB_NAME: 'dacs2022'
      SPRING_PROFILES_ACTIVE: 'prod'
  dbramon:
    container_name: dbramon
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'dacs2022'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    environment:
    - DB_HOST=db
    - DB_USER=root
    - DB_PASSWORD=root
    - DB_NAME=dacs2022
    - SPRING_PROFILE_ACTIVE=prod
