GET http://localhost:8081/api/v1/pacientes
###

GET http://localhost:8081/api/v1/pacientes/165

###

GET http://localhost:8081/api/v1/pacientes/nome/Ze

###
POST http://localhost:8081/api/v1/pacientes
content-Type: application/json

{
    "id": 0,
    "nome": "Zecão",
    "sexo": "Masculino",
    "dataNascimento": "2022-08-10T00:00:00"
}

###
PUT http://localhost:8081/api/v1/pacientes/165
content-Type: application/json

{
    "nome": "Zenelson",
    "sexo": "Masculino",
    "dataNascimento": "2022-08-10T00:00:00"
}

###

DELETE http://localhost:8081/api/v1/pacientes/300



###
GET http://localhost:8081/api/v1/medicos

###

GET http://localhost:8081/api/v1/medicos/161

###

GET http://localhost:8081/api/v1/medicos/nome/hu

###
POST http://localhost:8081/api/v1/medicos
content-Type: application/json

{
    "id": 0,
    "nome": "Amanda Garcia",
    "crm": 12313
}

###
PUT http://localhost:8081/api/v1/medicos/161
content-Type: application/json

{
    "crm": 5423
}

###

DELETE http://localhost:8081/api/v1/medicos/162

###
GET http://localhost:8081/api/v1/cidades

###

GET http://localhost:8081/api/v1/cidades/39

###

GET http://localhost:8081/api/v1/cidades/nome/Jo

###

POST http://localhost:8081/api/v1/cidades
content-Type: application/json

{
    "id": 0,
    "nome": "Curitiba"
}

###

PUT http://localhost:8081/api/v1/cidades/101
content-Type: application/json

{
    "nome": "São Paulo"
}

###

DELETE http://localhost:8081/api/v1/cidades/101


###

GET http://localhost:8081/api/v1/planos

###

GET http://localhost:8081/api/v1/planos/2

###
GET http://localhost:8081/api/v1/planos/nome/U

###

POST http://localhost:8081/api/v1/planos
content-Type: application/json

{
    "id": 0,
    "nome": "Herolife"
}

###

PUT http://localhost:8081/api/v1/planos/4
content-Type: application/json

{
    "nome": "HEROLIFE"
}

###

DELETE http://localhost:8081/api/v1/planos/4

###

GET http://localhost:8081/api/v1/procedimentos


###

GET http://localhost:8081/api/v1/procedimentos/33

###

GET http://localhost:8081/api/v1/procedimentos/descricao/C

###

POST http://localhost:8081/api/v1/procedimentos
content-Type: application/json

{
    "id": 0,
    "descricao": "Passo Suave"
}

###

PUT http://localhost:8081/api/v1/procedimentos/97
content-Type: application/json

{
    "descricao": "Corta Cura"
}

###

DELETE http://localhost:8081/api/v1/procedimentos/97
